version: 3.9

services:
  nb:
    build: .
    ports:
      -  "8888:8888"
    volumes:
      -  ./nb:usr/src/workspace/nb
    working_dir:
      -  usr/src/nb/
    entrypoint: ["jupyter","notebook","--ip='*'","--port=8888", "--no-browser", "--allow-root"]
